name: Publish
on:
  push:
  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - breadboard
          - breadboard-cli
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com/$GITHUB_REPOSITORY_OWNER'
      - run: npm install
        working-directory:  ${{ github.workspace }}
      - run: npm version --no-git-tag-version prepatch --preid=$(date +'%Y%m%d%H%M%S') --force
      - run: npm run build
      - run: npm publish --registry=https://npm.pkg.github.com/$GITHUB_REPOSITORY_OWNER
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


