name: Publish
on:
  push:
  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - breadboard
          - breadboard-cli
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com/'

      - run: npm install
        working-directory:  ${{ github.workspace }}

      - run: npm pkg set registry=https://npm.pkg.github.com/

      - run: echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - run: npm version --no-git-tag-version prepatch --preid=$(date +'%Y%m%d%H%M%S') --force

      - run: npm run build

      - run: npm pkg set name=@$OWNER_LC/${{ matrix.package }}

      - run: npm publish --@$OWNER_LC:registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


