name: Tests for Breadboard in an isolated environment
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BOARD: dl_board.json

jobs:
  test:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 21.x
          # - 20.x
          # - 19.x
          # - 18.x
        npm-version:
          - 10.x
          # - 9.x
          # - 8.x
          # - 7.x
          # - 6.x
        exclude:
          - node-version: 19.x
            npm-version: 9.x
          - node-version: 19.x
            npm-version: 10.x
        commands:
          - name: npx cli run
            script: |
              npx @exadev-io/breadboard-cli run $BOARD -i "{\"message\": \"Hello World\"}"

          - name: install + npx cli run
            script: |
              npm install -g @exadev-io/breadboard-cli
              npx @exadev-io/breadboard-cli run $BOARD -i "{\"message\": \"Hello World\"}"

          # - name: install + npx breadboard run
          #   script: |
          #     npm install -g @exadev-io/breadboard-cli
          #     npx breadboard run $BOARD -i "{\"message\": \"Hello World\"}"

          ##############################################################################################################

          # - name: npx cli mermaid
          #   script: |
          #     npx @exadev-io/breadboard-cli mermaid dl_board.json

          # - name: install + npx cli mermaid
          #   script: |
          #     npm install -g @exadev-io/breadboard-cli
          #     npx @exadev-io/breadboard-cli mermaid dl_board.json

          # - name: install + npx breadboard mermaid
          #   script: |
          #     npm install -g @exadev-io/breadboard-cli
          #     npx breadboard mermaid dl_board.json

          # ##############################################################################################################

          # - script: |
          #     npm init @exadev-io/breadboard test
          #   name: npm init

          # - script: |
          #     npx @exadev-io/create-breadboard test
          #   name: npx create

          # - script: |
          #     npm install -g @exadev-io/create-breadboard
          #     npx @exadev-io/create-breadboard test
          #   name: install + npx create

          # ##############################################################################################################

          # - script: |
          #     npm init @exadev-io/breadboard-kit test
          #   name: npm init kit

          # - script: |
          #     npx @exadev-io/create-breadboard-kit test
          #   name: npx create-kit

          # - script: |
          #     npm install -g @exadev-io/create-breadboard-kit
          #     npx @exadev-io/create-breadboard-kit test
          #   name: install + npx create-kit

    name: ${{ matrix.commands.name }} - Node ${{ matrix.node-version }} NPM ${{ matrix.npm-version }}
    steps:
      - run: echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com/'
          scope: $OWNER_LC
      - run: npm install -g npm@${{ matrix.npm-version }}
      - run: wget https://raw.githubusercontent.com/ExaDev-io/breadboard-samples/develop/samples/Breadboard%20Walkthrough/src/hello-world/board.json -O $BOARD
      - run: npm config set registry https://npm.pkg.github.com/
      - name: Run command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -ev
          ${{ matrix.commands.script }}
