name: Test currently deployed packages
on:
  release:
    types: [published]
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BOARD: dl_board.json

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@main
      - name: Set matrix data
        env:
          FILE: .github/fixtures/npx_scripts.json
        id: set-matrix
        run: echo "matrix=$(jq -c . < $FILE)" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 21.x
        fixtures: ${{ fromJson(needs.setup.outputs.matrix).fixtures }}
    name: "Should${{ matrix.fixtures.expect == 'fail' && ' not' || '' }} ${{ matrix.fixtures.name }}  - Node ${{ matrix.node-version }}"
    steps:
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}

      - name: Output YAML arary to temporary script file
        run: |
          echo "#!/bin/bash" > script.sh
          echo "set -xv" >> script.sh
          echo -e "${{ join(matrix.fixtures.script, '\n') }}" >> script.sh
          chmod +x script.sh

      - name: Show script content
        run: cat script.sh

      - name: Execute the script
        id: execute_script
        continue-on-error: ${{ matrix.fixtures.expect == 'fail' }}
        run: ./script.sh

      - if: ${{ steps.execute_script.outcome == 'success' && matrix.fixtures.expect == 'fail' }}
        run: echo "Test unexpectedly passed" && exit 1

      - if: ${{ steps.execute_script.outcome == 'failure' && matrix.fixtures.expect == 'fail' }}
        run: echo "This is expected to fail"
